#!/usr/bin/env python3
"""
Generate a JS module that exports a single SQL string containing a DO block
which converts every DateTime? column accidentally created as TEXT (by the
buggy _generated-tables.js before the is_relation() fix) back to TIMESTAMP(3).

The DO block uses per-column subtransactions so a failure on one column
doesn't abort the whole migration. Safe to re-run.

Output: scripts/_timestamp-fix.js (module.exports = '<sql string>')
"""
import re
from pathlib import Path

SCHEMA = Path(__file__).resolve().parent.parent / "prisma" / "schema.prisma"
GEN_JS = Path(__file__).resolve().parent / "_generated-tables.js"
OUT_JS = Path(__file__).resolve().parent / "_timestamp-fix.js"

PRIMITIVES = {"String", "Int", "BigInt", "Float", "Decimal", "Boolean",
              "DateTime", "Json", "Bytes"}


def main():
    text = SCHEMA.read_text()

    gen_text = GEN_JS.read_text() if GEN_JS.exists() else ""
    gen_tables = set(re.findall(r'CREATE TABLE IF NOT EXISTS "([A-Za-z]+)"', gen_text))

    fixes = []
    for m in re.finditer(r'^model\s+(\w+)\s*\{(.*?)^\}', text, re.MULTILINE | re.DOTALL):
        name = m.group(1)
        if name not in gen_tables:
            continue
        body = m.group(2)
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith('//') or line.startswith('@@') or line.startswith('@'):
                continue
            parts = line.split()
            if len(parts) < 2 or parts[0].startswith('@'):
                continue
            ftype = parts[1]
            if ftype.endswith('[]'):
                continue
            base = ftype.rstrip('?')
            if base not in PRIMITIVES:
                continue
            field_name = parts[0]
            if base == 'DateTime':
                fixes.append((name, field_name))

    # Build pairs array literal
    pairs_lines = []
    for i, (table, col) in enumerate(fixes):
        comma = ',' if i < len(fixes) - 1 else ''
        pairs_lines.append(f"    ['{table}', '{col}']{comma}")
    pairs_block = '\n'.join(pairs_lines)

    sql = f"""DO $$
DECLARE
  t text;
  c text;
  pairs text[][] := ARRAY[
{pairs_block}
  ];
BEGIN
  FOREACH t SLICE 1 IN pairs LOOP
    c := t[2];
    t := t[1];
    BEGIN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP(3) USING (%I)::TIMESTAMP(3)', t, c, c);
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Skipped %.%: %', t, c, SQLERRM;
    END;
  END LOOP;
END $$;"""

    # Escape backticks and ${} for JS template literal
    escaped = sql.replace("`", "\\`").replace("${", "\\${")

    js = f"""/**
 * AUTO-GENERATED by scripts/gen-text-to-timestamp-fix.py
 * Do not edit by hand — re-run the script instead.
 *
 * One-time fix: convert DateTime columns accidentally created as TEXT
 * (by the buggy is_relation() in gen-missing-tables.py before the "?"
 * suffix was stripped) back to TIMESTAMP(3).
 *
 * The DO block uses per-column subtransactions; failures are logged
 * as NOTICEs and don't abort the migration. Safe to re-run.
 */
module.exports = `{escaped}`;
"""

    OUT_JS.write_text(js)
    print(f"Generated {len(fixes)} ALTER statements → {OUT_JS}")


if __name__ == '__main__':
    main()
