import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();
async function main() {
  console.log('Seeding 3 Boxes HRMS...');
  const hp = await bcrypt.hash('admin123', 10);
  const p1 = await db.subscriptionPlan.upsert({where:{id:'plan-starter'},update:{},create:{id:'plan-starter',name:'Starter',planType:'starter',monthlyPrice:29,annualPrice:290,employeeLimit:50,companyLimit:1,branchLimit:5,status:'active'}});
  const p2 = await db.subscriptionPlan.upsert({where:{id:'plan-professional'},update:{},create:{id:'plan-professional',name:'Professional',planType:'professional',monthlyPrice:79,annualPrice:790,employeeLimit:200,companyLimit:3,branchLimit:20,payrollEnabled:true,recruitmentEnabled:true,attendanceEnabled:true,projectEnabled:true,clientPortalEnabled:true,status:'active'}});
  const p3 = await db.subscriptionPlan.upsert({where:{id:'plan-enterprise'},update:{},create:{id:'plan-enterprise',name:'Enterprise',planType:'enterprise',monthlyPrice:199,annualPrice:1990,employeeLimit:1000,companyLimit:10,branchLimit:100,payrollEnabled:true,recruitmentEnabled:true,attendanceEnabled:true,projectEnabled:true,clientPortalEnabled:true,vendorPortalEnabled:true,mobileAppEnabled:true,apiAccessEnabled:true,whiteLabelEnabled:true,status:'active'}});
  const t = await db.tenant.upsert({where:{tenantId:'3BOXES-CORP'},update:{},create:{tenantId:'3BOXES-CORP',name:'3 Boxes Corp',type:'enterprise',industry:'Technology',country:'India',currency:'INR',domain:'3boxes',status:'active',employeeLimit:500,storageLimit:10000,aiCreditLimit:500}});
  await db.subscription.upsert({where:{id:'sub-1'},update:{},create:{id:'sub-1',tenantId:t.id,planId:p3.id,startDate:new Date('2026-01-01'),endDate:new Date('2026-12-31'),status:'active',billingCycle:'annual',amount:1990}});
  await db.user.upsert({where:{email:'admin@3boxeshrms.com'},update:{},create:{email:'admin@3boxeshrms.com',password:hp,name:'3Boxes Admin',role:'super_admin',isActive:true,tenantId:t.id}});
  const cs = [];
  for (const [code,name,legal,city] of [['NEXTECH','3Boxes Technologies','3Boxes Technologies Pvt Ltd','Mumbai'],['NEXSOL','3Boxes Solutions','3Boxes Solutions India Pvt Ltd','Hyderabad'],['NEXSTAFF','3Boxes Staffing','3Boxes Staffing Services Pvt Ltd','Pune']]) {
    cs.push(await db.company.upsert({where:{code},update:{},create:{tenantId:t.id,code,name,legalName:legal,country:'India',currency:'INR',address:`${city}, India`,adminEmail:`admin@${code.toLowerCase()}.com`,status:'active'}}));
    await db.user.upsert({where:{email:`admin@${code.toLowerCase()}.com`},update:{},create:{email:`admin@${code.toLowerCase()}.com`,password:hp,name:`${name} Admin`,role:'company_admin',isActive:true,companyId:cs[cs.length-1].id}});
    await db.user.upsert({where:{email:`hr@${code.toLowerCase()}.com`},update:{},create:{email:`hr@${code.toLowerCase()}.com`,password:hp,name:`${name} HR`,role:'hr_admin',isActive:true,companyId:cs[cs.length-1].id}});
  }
  const bs = [];
  for (const [n,c,st,ci] of [['Mumbai HQ',0,'Maharashtra','Mumbai'],['Bangalore',0,'Karnataka','Bangalore'],['Delhi',1,'Delhi','New Delhi'],['Hyderabad',1,'Telangana','Hyderabad'],['Chennai',2,'Tamil Nadu','Chennai'],['Pune',2,'Maharashtra','Pune']]) { bs.push(await db.branch.create({data:{companyId:cs[c].id,name:n,country:'India',state:st,city:ci,address:`${ci}, ${st}`,status:'active'}})); }
  const ds = [], dgs = [];
  for (const c of cs) { for (const dn of ['Engineering','HR','Finance','Sales','Marketing','Operations','Quality','Admin']) { ds.push(await db.department.create({data:{companyId:c.id,name:dn,code:`${c.code}-${dn.substring(0,3).toUpperCase()}`,status:'active'}})); } for (const dn of ['Software Engineer','Senior Engineer','Tech Lead','HR Executive','HR Manager','Finance Manager','Sales Manager','Operations Manager']) { dgs.push(await db.designation.create({data:{companyId:c.id,name:dn,code:`${c.code}-${dn.replace(/\s/g,'').substring(0,4).toUpperCase()}`,status:'active'}})); } for (const g of [{n:'E1',c:'E1',mn:300000,mx:600000},{n:'E2',c:'E2',mn:600000,mx:1200000},{n:'E3',c:'E3',mn:1200000,mx:2000000},{n:'M1',c:'M1',mn:2000000,mx:3500000}]) { await db.grade.create({data:{companyId:c.id,name:g.n,code:g.c,salaryBandMin:g.mn,salaryBandMax:g.mx,status:'active'}}); } for (const s of [{n:'General',st:'09:00',e:'18:00'},{n:'Morning',st:'07:00',e:'16:00'},{n:'Evening',st:'14:00',e:'23:00'},{n:'Night',st:'22:00',e:'07:00'}]) { await db.shift.create({data:{companyId:c.id,name:s.n,startTime:s.st,endTime:s.e,status:'active'}}); } for (const lt of [{n:'Casual Leave',c:'CL',p:true,m:12},{n:'Sick Leave',c:'SL',p:true,m:10},{n:'Earned Leave',c:'EL',p:true,m:15},{n:'Maternity Leave',c:'ML',p:true,m:180},{n:'Paternity Leave',c:'PL',p:true,m:15}]) { await db.leaveType.create({data:{companyId:c.id,name:lt.n,code:lt.c,isPaid:lt.p,maxPerYear:lt.m}}); } }
  const fns = ['Aarav','Vikram','Priya','Ananya','Rohan','Meera','Arjun','Sneha','Rahul','Divya','Karthik','Neha','Suresh','Pooja','Amit'];
  const lns = ['Sharma','Patel','Reddy','Kumar','Joshi','Nair','Singh','Gupta','Verma','Iyer','Menon','Agarwal','Rao','Das','Chopra'];
  let ec = 0;
  for (let ci=0;ci<3;ci++) { const c=cs[ci]; const cd=ds.filter(d=>d.companyId===c.id); const cg=dgs.filter(d=>d.companyId===c.id); const cb=bs.filter(b=>b.companyId===c.id); for(let i=0;i<10;i++) { const fn=fns[ec%15],ln=lns[ec%15]; const sal=[500000,700000,900000,1200000,1500000,800000,600000,1100000,400000,1000000][i]; const ec2=`${c.code}${String(ec+1).padStart(4,'0')}`; const st=i<8?'active':(i<9?'onboarding':'exited'); try { await db.employee.create({data:{companyId:c.id,branchId:cb[i%cb.length].id,departmentId:cd[i%cd.length].id,designationId:cg[i%cg.length].id,employeeCode:ec2,firstName:fn,lastName:ln,email:`${fn.toLowerCase()}.${ln.toLowerCase()}@${c.code.toLowerCase()}.com`,phone:`+91-${9000000000+ec}`,gender:ec%3===0?'female':'male',dateOfBirth:new Date(1990+ec%10,ec%12,(ec%28)+1),nationality:'Indian',address:`${cb[i%cb.length].city}`,city:cb[i%cb.length].city,state:cb[i%cb.length].state,country:'India',employmentType:i%4===3?'contract':'full-time',status:st,joiningDate:new Date(2023+ec%3,ec%12,(ec%28)+1),probationEndDate:new Date(2024+ec%2,ec%12,(ec%28)+1),salary:sal,currency:'INR',bankName:['HDFC','SBI','ICICI','Axis'][ec%4],bankAccount:`${100000000000+ec}`,panNumber:`ABCP${String(ec).padStart(4,'0')}123F`,fatherName:`Mr. ${lns[(ec+1)%15]}`,emergencyContact:`+91-${8000000000+ec}`}}); ec++; } catch(e){console.error(`Emp error:${e.message}`);} } }
  for(let i=0;i<5;i++){const c=cs[i%3];const cd=ds.filter(d=>d.companyId===c.id);const cg=dgs.filter(d=>d.companyId===c.id);await db.requisition.create({data:{companyId:c.id,departmentId:cd[i%cd.length].id,designationId:cg[i%cg.length].id,positionType:i%2===0?'new':'replacement',numberOfOpenings:1+i%3,employmentType:'full-time',skillsRequired:['React','Python','HR','Java','AWS'][i],experienceRequired:`${2+i*2} years`,salaryBudget:500000+i*200000,priority:['low','medium','high','critical','medium'][i],approvalStatus:['pending','approved','approved','pending','approved'][i]}});}
  const jts=['Senior React Developer','Python Backend Engineer','HR Business Partner','Sales Executive','DevOps Engineer','Full Stack Developer','Data Analyst','Project Manager'];
  for(let i=0;i<8;i++){const c=cs[i%3];await db.job.create({data:{companyId:c.id,title:jts[i],description:`Looking for ${jts[i]}`,employmentType:i%3===2?'contract':'full-time',experienceRequired:`${2+i} years`,skillsRequired:['React','Python','HR','Sales','AWS','Node.js','SQL','PMP'][i],salaryMin:500000+i*100000,salaryMax:800000+i*150000,location:['Mumbai','Bangalore','Hyderabad','Delhi','Pune','Chennai','Mumbai','Bangalore'][i],workMode:['remote','hybrid','onsite','hybrid','remote','onsite','hybrid','remote'][i],status:i<6?'open':'closed'}});}
  for(let i=0;i<15;i++){const fn=fns[i],ln=lns[i],c=cs[i%3];await db.candidate.create({data:{companyId:c.id,firstName:fn,lastName:ln,email:`${fn.toLowerCase()}.${ln.toLowerCase()}@gmail.com`,mobile:`+91-${7000000000+i}`,source:['direct','vendor','referral','portal'][i%4],skills:['React, TypeScript','Python, Django','HR Management','Sales, CRM','AWS, Docker','Node.js, MongoDB','SQL, Python','PMP, Agile','React, Redux','Java, Spring','HR Ops','Marketing','DevOps','Data Science','Flutter'][i],experience:`${2+i%6} years`,currentCtc:400000+i*100000,expectedCtc:600000+i*120000,noticePeriod:`${1+i%3} months`,location:['Mumbai','Bangalore','Hyderabad','Delhi','Pune','Chennai','Mumbai','Bangalore','Hyderabad','Delhi','Pune','Chennai','Mumbai','Bangalore','Hyderabad'][i],recruiterStatus:['new','screened','shortlisted','rejected'][i%4],aiResumeScore:50+Math.random()*40}});}
  for(const [n,co,bt,bu] of [['3Boxes Platform','3BP-001','t_and_m',5000000],['Mobile App','3BM-002','fixed',2000000],['Client Portal','3BC-003','t_and_m',1500000],['Data Migration','3BD-004','fixed',800000],['AI Module','3BA-005','retainer',3000000]]){const e=await db.employee.findFirst({where:{companyId:cs[0].id}});await db.project.create({data:{companyId:cs[0].id,name:n,code:co,projectManagerId:e?.id,startDate:new Date('2026-01-01'),endDate:new Date('2026-12-31'),billingType:bt,budget:bu,estimatedHours:2000,status:'active',description:`${n} project`}});}
  for(const c of cs){const s=await db.salaryStructure.create({data:{companyId:c.id,name:'India Standard',description:'Standard salary structure'}});for(const[nm,tp,ct,fm,pct,tx,st] of [['Basic','earning','percentage','CTC*40%',40,true,false],['HRA','earning','percentage','Basic*50%',50,true,false],['Special Allowance','earning','formula','Gross-Basic-HRA-PF',null,true,false],['PF','deduction','percentage','Basic*12%',12,false,true],['Professional Tax','deduction','fixed','200',null,false,true]]){await db.salaryComponent.create({data:{companyId:c.id,structureId:s.id,name:nm,type:tp,calculationType:ct,formula:fm,percentage:pct,fixedAmount:nm==='Professional Tax'?200:0,isTaxable:tx,isStatutory:st}});}}
  for(const[n,co] of [['Infosys Consulting','INF-C'],['Wipro Solutions','WIP-C'],['TCS Digital','TCS-C'],['HCL Technologies','HCL-C'],['Tech Mahindra','TM-C']]){await db.client.create({data:{companyId:cs[0].id,name:n,code:co,industry:'IT Services',contactName:`Contact ${co}`,contactEmail:`contact@${co.toLowerCase()}.com`,status:'active'}});}
  const vs=[];for(const[n,co] of [['StaffFirst','SF-V'],['TalentPro','TP-V'],['HireRight','HR-V'],['SkillBridge','SB-V'],['PeopleFirst','PF-V']]){vs.push(await db.vendor.create({data:{companyId:cs[0].id,name:n,code:co,industry:'Staffing',contactName:`Contact ${co}`,contactEmail:`contact@${co.toLowerCase()}.com`,status:'active'}}));}
  for(let i=0;i<3;i++){await db.subVendor.create({data:{vendorId:vs[i].id,name:`SubVendor ${i+1}`,code:`SV-${i+1}`,contactName:`SV Contact ${i+1}`,status:'active'}});}
  for(const[tl,tp,ct,dur] of [['React Advanced','online','Engineering',40],['Leadership Excellence','classroom','Management',16],['Business Communication','online','Soft Skills',20],['Project Management Pro','online','Management',30],['Compliance & Ethics','online','Compliance',8]]){await db.course.create({data:{companyId:cs[0].id,title:tl,type:tp,category:ct,duration:dur,status:'active'}});}
  await db.reviewCycle.create({data:{companyId:cs[0].id,name:'Q1 2026 Review',startDate:new Date('2026-01-01'),endDate:new Date('2026-03-31'),status:'active'}});
  for(let i=0;i<10;i++){await db.ticket.create({data:{companyId:cs[i%3].id,category:['hr','it','payroll','hr','it'][i%5],priority:['low','medium','high','critical','medium'][i%5],subject:['Leave policy query','VPN access','Payslip issue','Onboarding docs','Email setup','PF balance','Hardware request','Attendance fix','Salary revision','Laptop issue'][i],status:['open','in_progress','resolved','open','in_progress','resolved','open','in_progress','resolved','closed'][i%10],description:`Ticket #${i+1}`}});}
  for(let i=0;i<10;i++){await db.notification.create({data:{companyId:cs[i%3].id,type:['leave','payroll','interview','task','system'][i%5],title:['Leave Approved','Payslip Generated','Interview Scheduled','Task Assigned','System Update'][i%5],message:`Notification #${i+1}`,read:i<5}});}
  console.log('Seed complete! Employees: '+ec+', Companies: '+cs.length);
  await db.$disconnect();
}
main().catch(e=>{console.error(e);db.$disconnect();process.exit(1);});
