import { NextResponse } from 'next/server';
import { getDb, getPlatformDb } from '@/lib/tenant-db';
import { verifyToken, getTokenFromHeaders } from '@/lib/auth';
import { ensureSchemaSynced, withSchemaSync } from '@/lib/schema-sync';

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  };
}

export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders() });
}

/**
 * GET /api/referrals
 *
 * Lists referrals created by the currently authenticated employee.
 *
 * The decoded JWT contains `userId` (User.id). We resolve the matching
 * Employee record (Employee.userId is unique) and return only that
 * employee's referrals — so employees only see their own referrals,
 * regardless of what referrerEmployeeId they might pass.
 *
 * Query params:
 *   - status: filter by status (pending | applied | interviewed | offered | hired | rejected | bonus_paid)
 *   - jobId: filter by jobPostingId
 */
export async function GET(request: Request) {
  const db = await getDb(request);
  try {
    const token = getTokenFromHeaders(request);
    if (!token) {
      return NextResponse.json(
        { error: 'No token provided' },
        { status: 401, headers: corsHeaders() }
      );
    }
    const decoded = await verifyToken(token);
    if (!decoded) {
      return NextResponse.json(
        { error: 'Invalid or expired token' },
        { status: 401, headers: corsHeaders() }
      );
    }

    await ensureSchemaSynced();

    // Resolve the employee record for this user — fail gracefully if
    // they don't have one yet (e.g. admins without an Employee row).
    const employee = await db.employee.findFirst({
      where: { userId: decoded.userId as string },
      select: { id: true },
    });
    if (!employee) {
      // No employee record → return an empty list (still 200) so the UI
      // doesn't crash trying to read .length off the referrals array.
      return NextResponse.json(
        { referrals: [], count: 0, message: 'No employee profile linked to this user.' },
        { headers: corsHeaders() }
      );
    }

    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const jobId = searchParams.get('jobId');

    const where: Record<string, unknown> = { referrerEmployeeId: employee.id };
    if (status) where.status = status;
    if (jobId) where.jobPostingId = jobId;

    const referrals = await withSchemaSync(() =>
      db.referral.findMany({
        where,
        include: {
          jobPosting: { select: { id: true, title: true, location: true, type: true } },
          referrerEmployee: {
            select: { id: true, firstName: true, lastName: true, employeeId: true },
          },
        },
        orderBy: { createdAt: 'desc' },
        take: 200,
      })
    );

    // Total bonus earned across this employee's paid-out referrals.
    // Used by the UI to show the "Total Bonus Earned" stat. We compute
    // it from the same dataset to avoid a second round-trip.
    const bonusPaidReferrals = referrals.filter(
      (r) => r.status === 'bonus_paid' && typeof r.bonusAmount === 'number'
    );
    const totalBonusEarned = bonusPaidReferrals.reduce(
      (sum, r) => sum + (r.bonusAmount as number),
      0
    );

    return NextResponse.json(
      {
        referrals,
        count: referrals.length,
        totalBonusEarned,
        bonusCurrency: 'INR',
      },
      { headers: corsHeaders() }
    );
  } catch (error) {
    console.error('Referrals GET error:', error);
    return NextResponse.json(
      { error: 'Internal server error', referrals: [] },
      { status: 500, headers: corsHeaders() }
    );
  }
}

/**
 * POST /api/referrals
 *
 * Create a new referral record. The referrer is ALWAYS the currently
 * authenticated employee — `referrerEmployeeId` is derived from the JWT,
 * never accepted from the request body (would be a privilege escalation
 * otherwise: an employee could attribute referrals to colleagues).
 *
 * Body:
 *   - jobPostingId: string (required)
 *   - candidateName: string (required)
 *   - candidateEmail: string (required)
 *   - candidatePhone: string (optional)
 *   - candidateResume: string (optional — typically a data URL)
 *   - notes: string (optional)
 *   - bonusAmount: number (optional — HR/Admin-set, defaults to null)
 *   - bonusCurrency: string (optional, default 'INR')
 *
 * `trackToken` is auto-generated by Prisma via @default(cuid()).
 */
export async function POST(request: Request) {
  const db = await getDb(request);
  try {
    const token = getTokenFromHeaders(request);
    if (!token) {
      return NextResponse.json(
        { error: 'No token provided' },
        { status: 401, headers: corsHeaders() }
      );
    }
    const decoded = await verifyToken(token);
    if (!decoded) {
      return NextResponse.json(
        { error: 'Invalid or expired token' },
        { status: 401, headers: corsHeaders() }
      );
    }

    await ensureSchemaSynced();

    const body = await request.json();
    const {
      jobPostingId,
      candidateName,
      candidateEmail,
      candidatePhone,
      candidateResume,
      notes,
      bonusAmount,
      bonusCurrency,
    } = body || {};

    if (!jobPostingId || typeof jobPostingId !== 'string') {
      return NextResponse.json(
        { error: 'jobPostingId is required' },
        { status: 400, headers: corsHeaders() }
      );
    }
    if (!candidateName || !String(candidateName).trim()) {
      return NextResponse.json(
        { error: 'candidateName is required' },
        { status: 400, headers: corsHeaders() }
      );
    }
    if (
      !candidateEmail ||
      !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(candidateEmail))
    ) {
      return NextResponse.json(
        { error: 'A valid candidateEmail is required' },
        { status: 400, headers: corsHeaders() }
      );
    }

    // Resolve the referrer Employee record from the JWT.
    const employee = await db.employee.findFirst({
      where: { userId: decoded.userId as string },
      select: { id: true, firstName: true, lastName: true },
    });
    if (!employee) {
      return NextResponse.json(
        { error: 'Your user account has no linked employee profile. Please contact HR.' },
        { status: 403, headers: corsHeaders() }
      );
    }

    // Verify the job posting actually exists so we don't create orphan referrals.
    const jobPosting = await db.jobPosting.findUnique({
      where: { id: jobPostingId },
      select: { id: true, title: true, status: true },
    });
    if (!jobPosting) {
      return NextResponse.json(
        { error: 'Job posting not found' },
        { status: 404, headers: corsHeaders() }
      );
    }

    // Parse bonusAmount defensively — accept number or numeric string.
    let bonusAmountNum: number | null = null;
    if (bonusAmount !== undefined && bonusAmount !== null && bonusAmount !== '') {
      const parsed = typeof bonusAmount === 'number'
        ? bonusAmount
        : parseFloat(String(bonusAmount));
      if (!Number.isNaN(parsed) && Number.isFinite(parsed)) {
        bonusAmountNum = parsed;
      }
    }

    const referral = await withSchemaSync(() =>
      db.referral.create({
        data: {
          jobPostingId,
          referrerEmployeeId: employee.id,
          candidateName: String(candidateName).trim(),
          candidateEmail: String(candidateEmail).toLowerCase().trim(),
          candidatePhone: candidatePhone ? String(candidatePhone).trim() : null,
          candidateResume: candidateResume || null,
          notes: notes ? String(notes) : null,
          bonusAmount: bonusAmountNum,
          bonusCurrency: bonusCurrency || 'INR',
          // trackToken: auto-generated by @default(cuid())
          status: 'pending',
        },
        include: {
          jobPosting: { select: { id: true, title: true } },
          referrerEmployee: {
            select: { id: true, firstName: true, lastName: true, employeeId: true },
          },
        },
      })
    );

    // Best-effort audit log — non-blocking.
    try {
      await db.auditLog.create({
        data: {
          userId: decoded.userId as string,
          action: 'CREATE_REFERRAL',
          module: 'referrals',
          details: `Referred ${candidateName} for "${jobPosting.title}"`,
        },
      });
    } catch {
      // Non-fatal
    }

    return NextResponse.json(
      { referral, trackToken: referral.trackToken },
      { status: 201, headers: corsHeaders() }
    );
  } catch (error) {
    console.error('Referrals POST error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500, headers: corsHeaders() }
    );
  }
}
